pipeline {
    agent none

    options {
        skipDefaultCheckout()
    }

    environment {
        TF_TOKEN_app_terraform_io = credentials('TFC_TOKEN')

        API_KEY_GODADDY       = credentials('API_KEY_GODADDY')
        API_SECRET_GODADDY    = credentials('API_SECRET_GODADDY')
        CUSTOMER_ID_GODADDY   = credentials('CUSTOMER_ID_GODADDY')
        DOMAIN                = credentials('DOMAIN')
    }

    stages {
        stage('Checkout') {
            agent { label 'docker' }
            steps {
                checkout scm
                stash name: 'source', includes: '**/*'
            }
        }

        stage('A1. Linting y validación') {
            agent { label 'terraform-awscli-checkov' }
            steps {
                unstash 'source'
                sh '''
                    cd iac
                    terraform fmt -check
                    terraform init -backend=false
                    terraform validate
                '''
            }
        }

        stage('A2. Prueba ligera') {
            agent { label 'terraform-awscli-checkov' }

            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    withEnv(['TF_WORKSPACE=dev']) {
                        sh '''
                            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                            export AWS_REGION=us-east-2
                            cd iac
                            terraform init
                            terraform workspace list
                            terraform workspace show
                            checkov --directory . -o junitxml --soft-fail --output-file-path results.xml
                            terraform plan
                        '''
                    }
                }
            }
        }

        stage('A3.1. Crear zona Route53 y actualizar DNS en GoDaddy') {
            agent { label 'terraform-awscli-checkov' }

            steps {
                unstash 'source'

                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials'],
                    string(credentialsId: 'API_KEY_GODADDY', variable: 'API_KEY_GODADDY'),
                    string(credentialsId: 'API_SECRET_GODADDY', variable: 'API_SECRET_GODADDY'),
                    string(credentialsId: 'CUSTOMER_ID_GODADDY', variable: 'CUSTOMER_ID_GODADDY'),
                    string(credentialsId: 'DOMAIN', variable: 'DOMAIN')
                ]) {

                    withEnv(['TF_WORKSPACE=dev']) {

                        sh '''
                            cd iac
                            terraform init
                            terraform apply -target=aws_route53_zone.main -auto-approve

                            terraform output -json route53_name_servers > ns.json
                            cat ns.json

                            echo '{"nameServers":' > payload.json
                            cat ns.json >> payload.json
                            echo '}' >> payload.json

                            cat payload.json

                            curl -X PUT "https://api.godaddy.com/v2/customers/$CUSTOMER_ID_GODADDY/domains/$DOMAIN/nameServers" \
                                -H "Authorization: sso-key '$API_KEY_GODADDY':'$API_SECRET_GODADDY'" \
                                -H "Content-Type: application/json" \
                                -H "X-Request-Id: $(uuidgen)" \
                                -d @payload.json
                        '''
                    }
                }
            }
        }

        stage('A3.2. Terminar el despliegue en dev') {
            agent { label 'terraform-awscli-checkov' }
            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    withEnv(['TF_WORKSPACE=dev']) {
                        sh '''
                            cd iac
                            terraform apply -auto-approve
                        '''
                    }
                }
                script {
                    env.cloudfront_distribution_id = sh(
                        script: "cd iac && terraform output -raw cloudfront_distribution_id",
                        returnStdout: true
                    ).trim()
                    stash name: 'source', includes: '**/*'
                }
            }
            post {
                failure {
                    echo "El apply falló. Ejecutando terraform destroy…"
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                        dir('iac') {
                            sh '''
                                terraform destroy -auto-approve -var-file=dev.tfvars
                            '''
                        }
                    }
                }
            }
        }

        stage('Invalidate Cache (CloudFront)') {
            agent { label 'terraform-awscli-checkov' }
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    echo "Invalidando caché de CloudFront ID: ${env.cloudfront_distribution_id}"
                    sh '''
                        aws --version
                        aws cloudfront create-invalidation --distribution-id $cloudfront_distribution_id --paths "/*"
                    '''
                }
            }
        }

        stage('A4. Prueba de integración de 1 sol') {
            agent { label 'terraform-awscli-checkov' }
            steps {
                unstash 'source'
                sh '''
                    for i in {1..10}; do
                    dig +nocmd +noall +answer api.cineagile.com @8.8.8.8
                    done
                '''
            }
        }

        stage('A5. Destruir dev') {
            agent { label 'terraform-awscli-checkov' }
            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform destroy
                    '''
                }
            }
        }

        stage('A6.1. Crear zona Route53 y actualizar DNS en GoDaddy') {
            agent { label 'terraform-awscli-checkov' }

            steps {
                unstash 'source'

                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials'],
                    string(credentialsId: 'API_KEY_GODADDY', variable: 'API_KEY_GODADDY'),
                    string(credentialsId: 'API_SECRET_GODADDY', variable: 'API_SECRET_GODADDY'),
                    string(credentialsId: 'CUSTOMER_ID_GODADDY', variable: 'CUSTOMER_ID_GODADDY'),
                    string(credentialsId: 'DOMAIN', variable: 'DOMAIN')
                ]) {

                    withEnv(['TF_WORKSPACE=dev']) {

                        sh '''
                            cd iac
                            terraform init
                            terraform apply -target=aws_route53_zone.main -auto-approve

                            terraform output -json route53_name_servers > ns.json
                            cat ns.json

                            echo '{"nameServers":' > payload.json
                            cat ns.json >> payload.json
                            echo '}' >> payload.json

                            cat payload.json

                            curl -X PUT "https://api.godaddy.com/v2/customers/$CUSTOMER_ID_GODADDY/domains/$DOMAIN/nameServers" \
                                -H "Authorization: sso-key '$API_KEY_GODADDY':'$API_SECRET_GODADDY'" \
                                -H "Content-Type: application/json" \
                                -H "X-Request-Id: $(uuidgen)" \
                                -d @payload.json
                        '''
                    }
                }
            }
        }

        stage('A6.2. Terminar el despliegue en qa') {
            agent { label 'terraform-awscli-checkov' }
            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform init
                        terraform apply -auto-approve
                    '''
                }
                stash name: 'tfstate', includes: 'terraform.tfstate'
            }
            post {
                failure {
                    echo "El apply falló. Ejecutando terraform destroy…"
                    withCsredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                        dir('iac') {
                            sh '''
                                terraform destroy -auto-approve -var-file=qa.tfvars
                            '''
                        }
                    }
                }
            }
        }

        stage('A7. Destruir qa') {
            agent { label 'terraform-awscli-checkov' }
            steps {
                unstash 'source'
                unstash 'tfstate'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform destroy
                    '''
                }
                stash name: 'tfstate', includes: 'terraform.tfstate'
            }
        }

        stage('A8. Prueba end to end de 1 sol') {
            agent { label 'docker' }
            steps {
                unstash 'source'
                unstash 'tfstate'
                sh '''
                    # Validar frontend
                    curl -s -o /dev/null -w "%{http_code}" https://www.cineagile.com

                    # Validar backend
                    curl -s -o /dev/null -w "%{http_code}" https://api.cineagile.com/health

                    # Revisar que devuelva 200 OK
                '''
            }
        }

        stage('A9.1. Crear zona Route53 y actualizar DNS en GoDaddy') {
            agent { label 'terraform-awscli-checkov' }

            steps {
                unstash 'source'

                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials'],
                    string(credentialsId: 'API_KEY_GODADDY', variable: 'API_KEY_GODADDY'),
                    string(credentialsId: 'API_SECRET_GODADDY', variable: 'API_SECRET_GODADDY'),
                    string(credentialsId: 'CUSTOMER_ID_GODADDY', variable: 'CUSTOMER_ID_GODADDY'),
                    string(credentialsId: 'DOMAIN', variable: 'DOMAIN')
                ]) {

                    withEnv(['TF_WORKSPACE=dev']) {

                        sh '''
                            cd iac
                            terraform init
                            terraform apply -target=aws_route53_zone.main -auto-approve

                            terraform output -json route53_name_servers > ns.json
                            cat ns.json

                            echo '{"nameServers":' > payload.json
                            cat ns.json >> payload.json
                            echo '}' >> payload.json

                            cat payload.json

                            curl -X PUT "https://api.godaddy.com/v2/customers/$CUSTOMER_ID_GODADDY/domains/$DOMAIN/nameServers" \
                                -H "Authorization: sso-key $API_KEY_GODADDY:$API_SECRET_GODADDY" \
                                -H "Content-Type: application/json" \
                                -H "X-Request-Id: $(uuidgen)" \
                                -d @payload.json
                        '''
                    }
                }
            }
        }

        stage('A9.2. Terminar el despliegue en prod') {
            agent { label 'terraform-awscli-checkov' }
            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform init
                        terraform apply -auto-approve
                    '''
                }
                stash name: 'tfstate', includes: 'terraform.tfstate'
            }
            post {
                failure {
                    echo "El apply falló. Ejecutando terraform destroy…"
                    withCsredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                        dir('iac') {
                            sh '''
                                terraform destroy -auto-approve -var-file=qa.tfvars
                            '''
                        }
                    }
                }
            }
        }

        stage('Run Playbook Dev') {
            agent { label 'ansible' }
            steps {
                sh '''
                     cd config
                     ansible-playbook -i ansible/inventory/dev \
                     ansible/playbooks/deploy_app.yml
                '''
            }
        }

    }

    post {
        success {
            echo 'Despliegue de infraestructura completado exitosamente.'
        }
        failure {
            echo 'Error en el despliegue del Frontend. Revisa la etapa fallida.'

        }
    }
}
