pipeline {
    agent none

    options {
        skipDefaultCheckout()
    }

    environment {
        TF_TOKEN_app_terraform_io = credentials('TFC_TOKEN')
    }

    stages {
        stage('Checkout') {
            agent { label 'docker' }
            steps {
                checkout scm
                stash name: 'source', includes: '**/*'
            }
        }

        // stage('A1. Linting y validación') {
        //     agent { label 'terraform' }
        //     steps {
        //         unstash 'source'
        //         sh '''
        //             cd iac
        //             terraform fmt -check
        //             terraform init -backend=false
        //             terraform validate
        //         '''
        //     }
        // }

        stage('A2. Prueba ligera') {
            agent { label 'terraform' }

            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform init
                        terraform workspace list
                        terraform workspace select dev
                        checkov --directory . -o junitxml --soft-fail --output-file-path results.xml
                        terraform plan -var-file=dev.tfvars -out=tfplan > plan.out
                        tail -n 10 plan.out
                    '''
                }
            }
        }

        stage('A3.1. Despliegue en dev: crear zona Route 53 (Cambiar dns godaddy)') {
            agent { label 'terraform' }
            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform init
                        terraform apply -target=aws_route53_zone.main -auto-approve -var-file=dev.tfvars
                    '''
                }
                stash name: 'source', includes: '**/*'
            }
        }

        stage('A3.2. Terminar el despliegue en dev') {
            agent { label 'terraform' }
            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        echo "Creando y validando el certificado SSL (2 min)"
                        terraform apply \
                            -target=aws_acm_certificate.cineagile_cert \
                            -target=aws_route53_record.cineagile_cert_validation \
                            -target=aws_acm_certificate_validation.cineagile_cert_validation \
                            -auto-approve -var-file=dev.tfvars
                        echo "Crear el bucket S3 y su configuración (rápido, segundos)"
                        terraform apply \
                            -target=aws_s3_bucket.frontend_bucket \
                            -target=aws_s3_bucket_server_side_encryption_configuration.frontend_encryption \
                            -target=aws_s3_bucket_website_configuration.website_config \
                            -target=aws_s3_bucket_public_access_block.block_public_access \
                            -auto-approve -var-file=dev.tfvars
                        echo "Crear CloudFront + OAC + política del bucket (5 min ejecución)"
                        terraform apply \
                            -target=aws_cloudfront_origin_access_control.oac \
                            -target=data.aws_iam_policy_document.s3_access_policy \
                            -target=aws_s3_bucket_policy.s3_access_policy \
                            -target=aws_cloudfront_response_headers_policy.security_headers \
                            -target=aws_cloudfront_distribution.s3_distribution \
                            -auto-approve -var-file=dev.tfvars
                        echo "Crear registros DNS principales (dominios -> distribución de cloudfront) (40 min propagación)"
                        terraform apply \
                            -target=aws_route53_record.root_domain \
                            -target=aws_route53_record.www_domain \
                            -auto-approve -var-file=dev.tfvars
                        echo "Preparando conexión global"
                        terraform apply \
                            -target=module.vpc_back_1_us_east_2 \
                            -target=module.vpc_back_2_us_east_1 \
                            -target=aws_lb.alb_us_east_1 \
                            -target=aws_lb.alb_us_east_2 \
                            -target=aws_lb_target_group.backend_us_east_1 \
                            -target=aws_lb_target_group.backend_us_east_2 \
                            -target=aws_lb_listener.https_us_east_1 \
                            -target=aws_lb_listener.https_us_east_2 \
                            -target=aws_route53_health_check.alb_us_east_1 \
                            -target=aws_route53_health_check.alb_us_east_2 \
                            -target=aws_route53_record.api_us_east_1 \
                            -target=aws_route53_record.api_us_east_2 \
                            -auto-approve -var-file=dev.tfvars
                        
                        terraform apply \
                            -target=aws_wafv2_web_acl.waf_acl \
                            -target=aws_wafv2_web_acl_association.wacl1 \
                            -target=aws_wafv2_web_acl_association.wacl2 \
                            -target=aws_kinesis_firehose_delivery_stream.waf_acl \
                            -target=aws_iam_role.firehose_role \
                            -target=aws_s3_bucket.waf_logs_s3
                            -auto-approve -var-file=dev.tfvars
                        
                        echo "Cloudfront"
                        terraform apply \
                            -target=aws_cloudwatch_log_group.frontend_access_logs \
                            -target=aws_iam_role.s3_to_cloudwatch_role \
                            -target=aws_iam_role_policy.s3_to_cloudwatch_policy \
                            -target=aws_cloudtrail.s3_access_trail \
                            -target=aws_route53_health_check.mi_servicio \
                            -target=aws_cloudwatch_dashboard.dashboard_cliente \
                            -auto-approve \
                            -var-file=dev.tfvars
                    '''
                }
                script {
                    env.cloudfront_distribution_id = sh(
                        script: "cd iac && terraform output -raw cloudfront_distribution_id",
                        returnStdout: true
                    ).trim()
                    stash name: 'source', includes: '**/*'
                }
            }
            post {
                failure {
                    echo "El apply falló. Ejecutando terraform destroy…"
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                        dir('iac') {
                            sh '''
                                terraform destroy -auto-approve -var-file=dev.tfvars
                            '''
                        }
                    }
                }
            }
        }

        stage('Invalidate Cache (CloudFront)') {
            agent { label 'terraform' }
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    echo "Invalidando caché de CloudFront ID: ${env.cloudfront_distribution_id}"
                    sh '''
                        aws --version
                        aws cloudfront create-invalidation --distribution-id $cloudfront_distribution_id --paths "/*"
                    '''
                }
            }
        }

        stage('A4. Prueba de integración de 1 sol') {
            agent { label 'terraform' }
            steps {
                unstash 'source'
                sh '''
                    for i in {1..10}; do
                    dig +nocmd +noall +answer api.cineagile.com @8.8.8.8
                    done
                '''
            }
        }

        stage('A5. Destruir dev') {
            agent { label 'terraform' }
            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform destroy
                    '''
                }
            }
        }

        stage('A6.1. Despliegue en qa: crear zona Route 53 (Cambiar dns godaddy)') {
            agent { label 'terraform' }
            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform init
                        terraform apply -target=aws_route53_zone.main -auto-approve -var-file=qa.tfvars
                    '''
                }
                stash name: 'source', includes: '**/*'
            }
            post {
                failure {
                    echo "El apply falló. Ejecutando terraform destroy…"
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                        dir('iac') {
                            sh '''
                                terraform destroy -auto-approve -var-file=qa.tfvars
                            '''
                        }
                    }
                }
            }
        }

        stage('A6.2. Terminar el despliegue en qa') {
            agent { label 'terraform' }
            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform init
                        echo "Creando y validando el certificado SSL (2 min)"
                        terraform apply \
                            -target=aws_acm_certificate.cineagile_cert \
                            -target=aws_route53_record.cineagile_cert_validation \
                            -target=aws_acm_certificate_validation.cineagile_cert_validation \
                            -auto-approve -var-file=qa.tfvars
                        echo "Crear el bucket S3 y su configuración (rápido, segundos)"
                        terraform apply \
                            -target=aws_s3_bucket.frontend_bucket \
                            -target=aws_s3_bucket_server_side_encryption_configuration.frontend_encryption \
                            -target=aws_s3_bucket_website_configuration.website_config \
                            -target=aws_s3_bucket_public_access_block.block_public_access \
                            -auto-approve -var-file=qa.tfvars
                        echo "Crear CloudFront + OAC + política del bucket (5 min ejecución)"
                        terraform apply \
                            -target=aws_cloudfront_origin_access_control.oac \
                            -target=data.aws_iam_policy_document.s3_access_policy \
                            -target=aws_s3_bucket_policy.s3_access_policy \
                            -target=aws_cloudfront_response_headers_policy.security_headers \
                            -target=aws_cloudfront_distribution.s3_distribution \
                            -auto-approve -var-file=qa.tfvars
                        echo "Crear registros DNS principales (dominios -> distribución de cloudfront) (40 min propagación)"
                        terraform apply \
                            -target=aws_route53_record.root_domain \
                            -target=aws_route53_record.www_domain \
                            -auto-approve -var-file=qa.tfvars
                        echo "Preparando conexión global"
                        terraform apply \
                            -target=module.vpc_back_1_us_east_2 \
                            -target=module.vpc_back_2_us_east_1 \
                            -target=aws_lb.alb_us_east_1 \
                            -target=aws_lb.alb_us_east_2 \
                            -target=aws_lb_target_group.backend_us_east_1 \
                            -target=aws_lb_target_group.backend_us_east_2 \
                            -target=aws_lb_listener.https_us_east_1 \
                            -target=aws_lb_listener.https_us_east_2 \
                            -target=aws_route53_health_check.alb_us_east_1 \
                            -target=aws_route53_health_check.alb_us_east_2 \
                            -target=aws_route53_record.api_us_east_1 \
                            -target=aws_route53_record.api_us_east_2 \
                            -auto-approve -var-file=qa.tfvars
                        
                        terraform apply \
                            -target=aws_wafv2_web_acl.waf_acl \
                            -target=aws_wafv2_web_acl_association.wacl1 \
                            -target=aws_wafv2_web_acl_association.wacl2 \
                            -target=aws_kinesis_firehose_delivery_stream.waf_acl \
                            -target=aws_iam_role.firehose_role \
                            -target=aws_s3_bucket.waf_logs_s3
                            -auto-approve -var-file=qa.tfvars
                    '''
                }
                stash name: 'tfstate', includes: 'terraform.tfstate'
            }
            post {
                failure {
                    echo "El apply falló. Ejecutando terraform destroy…"
                    withCsredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                        dir('iac') {
                            sh '''
                                terraform destroy -auto-approve -var-file=qa.tfvars
                            '''
                        }
                    }
                }
            }
        }

        stage('A7. Destruir qa') {
            agent { label 'terraform' }
            steps {
                unstash 'source'
                unstash 'tfstate'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform destroy
                    '''
                }
                stash name: 'tfstate', includes: 'terraform.tfstate'
            }
        }

        stage('A8. Prueba end to end de 1 sol') {
            agent { label 'docker' }
            steps {
                unstash 'source'
                unstash 'tfstate'
                sh '''
                    # Validar frontend
                    curl -s -o /dev/null -w "%{http_code}" https://www.cineagile.com

                    # Validar backend
                    curl -s -o /dev/null -w "%{http_code}" https://api.cineagile.com/health

                    # Revisar que devuelva 200 OK
                '''
            }
        }

        stage('A9.1. Despliegue en prod: crear zona Route 53 (Cambiar dns en godaddy)') {
            agent { label 'terraform' }
            steps {
                unstash 'source'
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                    sh '''
                        cd iac
                        terraform init
                        terraform apply -target=aws_route53_zone.main -auto-approve -var-file=prod.tfvars
                    '''
                }
                stash name: 'source', includes: '**/*'
            }
            post {
                failure {
                    echo "El apply falló. Ejecutando terraform destroy…"
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]){
                        dir('iac') {
                            sh '''
                                terraform destroy -auto-approve -var-file=qa.tfvars
                            '''
                        }
                    }
                }
            }
        }

        // stage('Run Playbook Dev') {
        //     agent { label 'ansible' }
        //     steps {
        //         sh '''
        //         ansible-playbook \
        //             -i ansible/inventory/dev \
        //             ansible/playbooks/deploy_app.yml
        //         '''
        //     }
        // }

    }

    post {
        success {
            echo 'Despliegue de infraestructura completado exitosamente.'
        }
        failure {
            echo 'Error en el despliegue del Frontend. Revisa la etapa fallida.'

        }
    }
}