jenkins:
  systemMessage: "Jenkins Configured with Dynamic Agents"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  clouds:
    - docker:
        name: "docker-dind-cloud"
        dockerApi:
          dockerHost:
            uri: "tcp://172.18.0.1:2375"
        exposeDockerHost: true

        templates:

          # === Agente Docker CLI ===
          - name: "docker-agent"
            labelString: "docker"
            remoteFs: "/home/jenkins"
            instanceCapStr: 5
            dockerTemplateBase:
              image: "jenkins/inbound-agent:alpine3.22-jdk21"
              tty: true
              # mounts:
              #   - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"

              memoryLimit: 4096        # 4GB
              memorySwap: 5120         # 5GB
              cpuShares: 2048 
            retentionStrategy:
              idleMinutes: 10
            connector:
              attach:
                user: "jenkins"

          # === Agente Jenkins inbound (genérico) ===
          - name: "docker-agent2"
            labelString: "docker2"
            remoteFs: "/home/jenkins"
            instanceCapStr: 5
            dockerTemplateBase:
              image: "jenkins/inbound-agent:alpine3.22-jdk21"
              tty: true
            retentionStrategy:
              idleMinutes: 10

          # === Agente Git ===
          - name: "docker-agent3"
            labelString: "docker4"
            remoteFs: "/home/jenkins"
            instanceCapStr: 5
            dockerTemplateBase:
              image: "alpine/git:2.49.1"
              tty: true
            retentionStrategy:
              idleMinutes: 1

          # === Agente NodeJS ===
          - name: "node-agent"
            labelString: "node"
            remoteFs: "/home/node"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "node:iron-alpine3.22"
              tty: true
            retentionStrategy:
              idleMinutes: 5
            connector:
              attach:
                user: "root"

          # === Agente AWS CLI ===
          - name: "aws-agent"
            labelString: "aws"
            remoteFs: "/home/aws"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "amazon/aws-cli:2.32.6"
              tty: true
            retentionStrategy:
              idleMinutes: 5
            connector:
              attach:
                user: "jenkins"

          # === Agente Terraform ===
          - name: "terraform-agent"
            labelString: "terraform"
            remoteFs: "/home"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "logiquenoire/jenkins-agent-cineagile:1.0"
              tty: true
            retentionStrategy:
              idleMinutes: 5
            connector:
              attach:
                user: "root"
credentials:
  system:
    domainCredentials:
      - credentials:
        - aws:
            scope: GLOBAL
            id: "aws_credentials"
            accessKey: ${AWS_ACCESS_KEY_ID}
            secretKey: AWS_SECREY_KEY_ACCESS
jobs:
  - script: >
      pipelineJob('iac') {
        definition {
          cpsScm {
            scm {
              git {
                branch('*/main')
                remote {
                  url('${REPOSITORY_URL}')
                }
              }
            }
            scriptPath('pipelines/iac/Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('back') {
        definition {
          cpsScm {
            scm {
              git {
                branch('*/main')
                remote {
                  url('${REPOSITORY_URL}')
                }
              }
            }
            scriptPath('pipelines/backend/Jenkinsfile')
          }
        }
      }


tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git

