jenkins:
  systemMessage: "Jenkins initial configuration"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  clouds:
    - docker:
        name: "docker-dind-cloud"
        dockerApi:
          dockerHost:
            uri: "tcp://dind:2375"
        exposeDockerHost: true
        templates:
          # === Agente Docker (General) ===
          - name: "docker-agent"
            labelString: "docker"
            remoteFs: "/home/jenkins"
            instanceCapStr: 5
            dockerTemplateBase:
              image: "jenkins/inbound-agent:4.35-3"
              tty: true
              # Sintaxis estándar volumen: "host_path:container_path"
              mounts:
                - "/var/run/docker.sock:/var/run/docker.sock"
            retentionStrategy:
              idleMinutes: 1

          # === Agente Docker2 ===
          - name: "docker-agent2"
            labelString: "docker-agent2"
            remoteFs: "/home/jenkins"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "jenkins/inbound-agent:4.35-3"
              tty: true
              mounts:
                - "/var/run/docker.sock:/var/run/docker.sock"
            retentionStrategy:
              idleMinutes: 1

          # === Agente AWS CLI ===
          - name: "awscli-agent"
            labelString: "awscli"
            remoteFs: "/home/jenkins"
            instanceCapStr: 5
            dockerTemplateBase:
              image: "amazon/aws-cli:2.32.6" # Usamos la imagen normal
              tty: true
              # DESCOMENTAR ESTO es vital para el truco:
              mounts:
                - "/var/run/docker.sock:/var/run/docker.sock"
            retentionStrategy:
              idleMinutes: 1

# Configuración para Job DSL Plugin
jobs:
  - file: /var/jenkins_home/casc_configs/seed.groovy