jenkins:
  systemMessage: "Jenkins Configured with Dynamic Agents"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  clouds:
    - docker:
        name: "docker-dind-cloud"
        dockerApi:
          dockerHost:
            uri: "tcp://172.18.0.1:2375"
        exposeDockerHost: true

        templates:

          # === Agente Docker CLI ===
          - name: "docker-agent"
            labelString: "docker"
            remoteFs: "/home/jenkins"
            instanceCapStr: 5
            dockerTemplateBase:
              image: "jenkins/inbound-agent:alpine3.22-jdk21"
              tty: true
              # mounts:
              #   - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"

              memoryLimit: 4096        # 4GB
              memorySwap: 5120         # 5GB
              cpuShares: 2048 
            retentionStrategy:
              idleMinutes: 10
            connector:
              attach:
                user: "jenkins"
          
          # === Agente Terraform AWSCLI Checkov ===
          - name: "terraform-agent"
            labelString: "terraform"
            remoteFs: "/home"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "logiquenoire/jenkins-agent-cineagile:terraform-awscli-checkov-1.0"
              tty: true
            retentionStrategy:
              idleMinutes: 5
            connector:
              attach:
                user: "root"

          # === Agente NodeJS ===
          - name: "node-agent"
            labelString: "node"
            remoteFs: "/home"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "logiquenoire/jenkins-agent-cineagile:node-1.0"
              tty: true
            retentionStrategy:
              idleMinutes: 5
            connector:
              attach:
                user: "root"
          
credentials:
  system:
    domainCredentials:
      - credentials:
        - aws:
            scope: GLOBAL
            id: "aws_credentials"
            accessKey: ${AWS_ACCESS_KEY_ID}
            secretKey: ${AWS_SECRET_KEY_ACCESS}
        - string:
            scope: GLOBAL
            id: "TFC_TOKEN"
            secret: "${TFC_TOKEN}"
jobs:
  - script: >
      pipelineJob('prueba') {
        definition {
          cpsScm {
            scm {
              git {
                branch('*/main')
                remote {
                  url('${REPOSITORY_URL}')
                }
              }
            }
            scriptPath('pipelines/iac/Jenkinsfile')
          }
        }
      }
  
  # - script: >
  #     pipelineJob('back') {
  #       definition {
  #         cpsScm {
  #           scm {
  #             git {
  #               branch('*/main')
  #               remote {
  #                 url('${REPOSITORY_URL}')
  #               }
  #             }
  #           }
  #           scriptPath('pipelines/backend/Jenkinsfile')
  #         }
  #       }
  #     }


tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git

