jenkins:
  systemMessage: "Jenkins initial configuration"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  nodes:
    # Agente Docker
    - permanent:
        name: "docker-agent"
        labelString: "docker"
        mode: NORMAL
        remoteFS: "/home/jenkins"
        numExecutors: 2
        launcher:
          inbound:
            webSocket: true
            workDirSettings:
              disabled: true
              internalDir: "remoting"
              workDirPath: "/tmp"

    # Agente Node.js
    - permanent:
        name: "node-agent"
        labelString: "node"
        mode: NORMAL
        remoteFS: "/home/jenkins"
        numExecutors: 2
        launcher:
          inbound:
            webSocket: true
            workDirSettings:
              disabled: true
              internalDir: "remoting"
              workDirPath: "/tmp"

    # Agente GIT AWS CLI
    - permanent:
        name: "git-awscli-agent"
        labelString: "git-awscli"
        mode: NORMAL
        remoteFS: "/home/jenkins"
        numExecutors: 1
        launcher:
          inbound:
            webSocket: true
            workDirSettings:
              disabled: true
              internalDir: "remoting"
              workDirPath: "/tmp"
jobs:
  - file: /var/jenkins_home/casc_configs/seed.groovy