jenkins:
  systemMessage: "Jenkins Configured with Dynamic Agents"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  clouds:
    - docker:
        name: "docker-dind-cloud"
        dockerApi:
          dockerHost:
            uri: "tcp://172.18.0.1:2375"
        exposeDockerHost: true

        templates:

          # === Agente Docker CLI ===
          - name: "docker-agent"
            labelString: "docker"
            remoteFs: "/home/jenkins"
            instanceCapStr: 5
            dockerTemplateBase:
              image: "docker:29.0.4-cli"
              tty: true
              mounts:
                - "/var/run/docker.sock:/var/run/docker.sock"
            retentionStrategy:
              idleMinutes: 1

          # === Agente Jenkins inbound (genérico) ===
          - name: "docker-agent2"
            labelString: "docker2"
            remoteFs: "/home/jenkins"
            instanceCapStr: 5
            dockerTemplateBase:
              image: "jenkins/inbound-agent:4.35-3"
              tty: true
            retentionStrategy:
              idleMinutes: 1

          # === Agente Git ===
          - name: "docker-agent3"
            labelString: "docker3"
            remoteFs: "/home/jenkins"
            instanceCapStr: 5
            dockerTemplateBase:
              image: "alpine/git:2.49.1"
              tty: true
            retentionStrategy:
              idleMinutes: 1

          # === Agente NodeJS ===
          - name: "node-agent"
            labelString: "node"
            remoteFs: "/home/jenkins"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "node:iron-alpine3.22"
              tty: true
            retentionStrategy:
              idleMinutes: 5

          # === Agente AWS CLI ===
          - name: "aws-agent"
            labelString: "aws"
            remoteFs: "/home/jenkins"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "amazon/aws-cli:2.32.6"
              tty: true
            retentionStrategy:
              idleMinutes: 5

          # === Agente Terraform ===
          - name: "terraform-agent"
            labelString: "terraform"
            remoteFs: "/home/jenkins"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "hashicorp/terraform:1.14"
              tty: true
            retentionStrategy:
              idleMinutes: 5

jobs:
  - file: /var/jenkins_home/casc_configs/seed.groovy